// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yygmespagnhdlcubtrdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Z21lc3BhZ25oZGxjdWJ0cmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODU0NTMsImV4cCI6MjA1NzQ2MTQ1M30.a6S2fwOz1ox6lRHgroLaZKJJi8aJe46caPmzh1CrqEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);